name: Feature Request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Got an idea for improving OpenZenith? Let us know!

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: Short description of your idea
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Explain the use case and benefit

  - type: textarea
    id: design
    attributes:
      label: Proposed Design
      description: Describe how it might work (code, GUI, data, etc.)
